services:
  - type: web
    name: hagz-yomi
    runtime: node
    plan: free
    buildCommand: npm run setup-supabase && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /
